const chatMessage = {
  message_id: 'm1',
  message_type: 'ai_response',
  content_text: 'Test response Search results SQL result',
  evidence_refs: [],
  data_quality_warnings: [],
  tool_params: {},
  suggested_followups: [],
  created_at: new Date().toISOString(),
};

const forecastData = [
  { date: 'Day 1', predicted: 25, upper: 30, lower: 20, actual: 24, category: 'Theft', district: 'Bengaluru Urban' },
];

export const api = {
  login: jest.fn().mockResolvedValue({
    token: 't',
    user: { user_id: '1', kgid: '1', first_name: 'Test', role_id: 1, role_name: 'Investigator' },
  }),
  chatQuery: jest.fn().mockResolvedValue(chatMessage),
  getDashboardKpis: jest.fn().mockResolvedValue([
    { label: 'Total FIRs', value: '12,847', change: '+12.4%', icon: 'FileText' },
    { label: 'Active Cases', value: '156', change: '-8.2%', icon: 'Activity' },
  ]),
  getActivityFeed: jest.fn().mockResolvedValue([{ id: 'f1', text: 'Recent activity', time: '2 min ago', type: 'case' }]),
  getTrends: jest.fn().mockResolvedValue([{ period: '2024-01', count: 200, crime_type: 'Theft' }]),
  getHotspots: jest.fn().mockResolvedValue([
    { cluster_id: 1, centroid_lat: 12.9716, centroid_lng: 77.5946, case_count: 12, radius_km: 0.8, crime_type: 'Theft' },
  ]),
  getForecastData: jest.fn().mockResolvedValue(forecastData),
  getMultiForecast: jest.fn().mockResolvedValue([{ category: 'Theft', data: forecastData }]),
  getDistrictForecasts: jest.fn().mockResolvedValue([{ district: 'Bengaluru Urban', data: forecastData }]),
  getAlerts: jest.fn().mockResolvedValue([
    { id: 'a1', severity: 'critical', title: 'Test Alert', description: 'Test description', rule_id: 'R1', trigger_condition: '>25%', created_at: new Date().toISOString(), acknowledged: false },
  ]),
  getNetwork: jest.fn().mockImplementation((_name: string, _searchType?: string) => Promise.resolve({
    nodes: [
      { id: 'case_101', label: 'Case #101', node_type: 'case', cases: 3, crime_type: 'Theft', risk_tier: 'LOW', sub_label: 'Theft' },
      { id: 'case_102', label: 'Case #102', node_type: 'case', cases: 2, crime_type: 'Theft', risk_tier: 'LOW', sub_label: 'Theft' },
      { id: 'node_0', label: 'Ravi Kumar', node_type: 'accused', cases: 3, risk_tier: 'ELEVATED', crime_type: 'Theft', person_id: 'Ravi Kumar', sub_label: '3 cases' },
      { id: 'node_1', label: 'Suresh P', node_type: 'accused', cases: 2, risk_tier: 'MODERATE', crime_type: 'Robbery', person_id: 'Suresh P', sub_label: '2 cases' },
    ],
    edges: [
      { id: 'edge_0', source: 'case_101', target: 'node_0', weight: 1, shared_cases: [101], connection_basis: 'accused in Case #101' },
      { id: 'edge_1', source: 'case_101', target: 'node_1', weight: 1, shared_cases: [101], connection_basis: 'accused in Case #101' },
      { id: 'edge_2', source: 'case_102', target: 'node_0', weight: 1, shared_cases: [102], connection_basis: 'accused in Case #102' },
      { id: 'edge_3', source: 'case_101', target: 'case_102', weight: 1, shared_cases: [101, 102], connection_basis: 'shared: Ravi Kumar', edge_type: 'case_case' },
    ],
  })),
  networkAiQuery: jest.fn().mockResolvedValue({ answer: 'Analysis complete.', summary: '2 criminals, 1 connection.' }),
  getOffenderProfile: jest.fn().mockResolvedValue({
    entity_name: 'Ravi Kumar',
    total_score: 56,
    risk_tier: 'ELEVATED',
    features: [],
    linked_cases: [{ case_id: 101, crime_no: 'CN1', crime_type: 'Theft', year: 2024, status: 'Open' }],
    disclaimer: 'Analytical tool',
  }),
  createOffenderProfile: jest.fn().mockResolvedValue({ status: 'success' }),
  getPriorityScore: jest.fn().mockReturnValue({ total_score: 56, risk_tier: 'ELEVATED', features: [], disclaimer: 'Analytical tool' }),
  listInbox: jest.fn().mockResolvedValue([
    { message_id: 'm1', type: 'STATUS_UPDATE', subject: 'Test Subject', body: 'Body', priority: 'HIGH', status: 'SENT', created_at: new Date().toISOString(), sender: {}, recipients: [], cc: [], linked_resources: [], attachments: [] },
  ]),
  sendMessage: jest.fn().mockResolvedValue({ message_id: 'm2', subject: 'Update' }),
  markRead: jest.fn().mockResolvedValue(true),
  acknowledgeMessage: jest.fn().mockResolvedValue(true),
  getMessage: jest.fn().mockResolvedValue({ message_id: 'm1', subject: 'Test Subject', body: 'Body' }),
  getThread: jest.fn().mockResolvedValue([]),
  checkPermission: jest.fn().mockResolvedValue({ resource_type: 'CASE', action: 'VIEW', allowed: true }),
  delegatePermission: jest.fn().mockResolvedValue({ permission_id: 'p1', status: 'active' }),
  revokeDelegation: jest.fn().mockResolvedValue(true),
  listDelegations: jest.fn().mockResolvedValue([]),
  setEmergency: jest.fn().mockResolvedValue(false),
  getEmergencyStatus: jest.fn().mockResolvedValue(false),
  listDynamicGroups: jest.fn().mockResolvedValue([{ group_id: 'g1', group_name: 'Task Force Alpha', group_type: 'task_force', status: 'active', lead_employee_id: 1, linked_case_ids: [], linked_offender_ids: [], created_at: new Date().toISOString() }]),
  createDynamicGroup: jest.fn().mockResolvedValue({ group_id: 'g2', group_name: 'New Group', status: 'active' }),
  dissolveGroup: jest.fn().mockResolvedValue(true),
  addGroupMember: jest.fn().mockResolvedValue({ employee_id: 1, role_in_group: 'member' }),
  removeGroupMember: jest.fn().mockResolvedValue(true),
  listGroupMembers: jest.fn().mockResolvedValue([]),
  listMyGroups: jest.fn().mockResolvedValue([]),
  listCoordination: jest.fn().mockResolvedValue([{ request_id: 'c1', request_type: 'ASSISTANCE', description: 'Assistance needed', priority: 'HIGH', status: 'pending', created_at: new Date().toISOString() }]),
  createCoordination: jest.fn().mockResolvedValue({ request_id: 'c2', status: 'pending' }),
  updateCoordination: jest.fn().mockResolvedValue(true),
  listAuditLog: jest.fn().mockResolvedValue([{ entry_id: 'a1', timestamp: new Date().toISOString(), event_type: 'LOGIN', category: 'authentication', actor_kgid: 'user1', actor_role: 'Investigator', resource_type: 'system', resource_id: '', detail: 'User logged in', result: 'success' }]),
  listModels: jest.fn().mockResolvedValue([{ model_id: 'm1', model_name: 'GLM', model_version: 'v1', provider: 'Zoho', capabilities: [], parameters: {}, created_at: new Date().toISOString() }]),
  listAgentCapabilities: jest.fn().mockResolvedValue([{ agent_name: 'database_query', intents: ['database_query'], description: 'Query FIR database', required_permissions: [] }]),
  listMissions: jest.fn().mockResolvedValue([]),
  getMission: jest.fn().mockResolvedValue({ mission: { mission_id: 'mission-1', status: 'completed' }, tasks: [] }),
  listClaims: jest.fn().mockResolvedValue([]),
  addClaim: jest.fn().mockResolvedValue({ claim_id: 'claim-1' }),
  updateClaimStatus: jest.fn().mockResolvedValue({ status: 'ok' }),
  commanderQuery: jest.fn().mockResolvedValue({ mission_id: 'mission-1', intents: {}, tasks: [], summary: 'Mission complete', status: 'completed' }),
  createInvestigation: jest.fn().mockResolvedValue({ investigation_id: 'inv-2', title: 'New Investigation', status: 'open', created_at: new Date().toISOString() }),
  listInvestigations: jest.fn().mockResolvedValue([{ investigation_id: 'inv-1', title: 'Test Investigation', status: 'open', created_at: new Date().toISOString(), case_count: 1, query_count: 0 }]),
  getInvestigation: jest.fn().mockResolvedValue({ investigation_id: 'inv-1', title: 'Test Investigation', status: 'open', created_at: new Date().toISOString(), cases: [] }),
  addCaseToInvestigation: jest.fn().mockResolvedValue({ status: 'ok' }),
  getCaseSimilarity: jest.fn().mockResolvedValue([{ case_master_id: 102, similarity_score: 0.82, crime_no: 'CN2', crime_sub_head: 'Theft', crime_registered_date: '2024-01-01', district_name: 'Bangalore', per_feature_scores: {} }]),
  getCaseLeads: jest.fn().mockResolvedValue([]),
  getCaseTimeline: jest.fn().mockResolvedValue([]),
  generateInvestigationReport: jest.fn().mockResolvedValue({ job_id: 'job-1', status: 'completed', created_at: new Date().toISOString() }),
};


